### ISSUE TITLE
rpm repo -proxy

### ISSUE THREAD

**Issue by preethit** [RedHatQE/pulp-automation#23]
Setup a proxy
Create a repo with required  and verifications options
use proxy options on repo create
Feed Proxy
  --proxy-host - hostname of the proxy server to use
  --proxy-port - port on the proxy server to make requests
  --proxy-user - username used to authenticate with the proxy server
  --proxy-pass - password used to authenticate with the proxy server
  
Pulp-admin rpm repo create --repo-id foo --feed http://myurl    --proxy-host http://pulp-upgrade-testing.usersys.redhat.com --proxy-port 3128

**Comment by dparalen** [comment]
@preethit is the goal to create an API or CLI test case?

**Comment by preethit** [comment]
Since we do not have any automation around CLI I would say let us start
with the API.

**Comment by dparalen** [comment]
@preethit the test case is legit but it is rather a set-up/deployment thing than a scenario.
Actually, this is what the testcase would look like reusing current rpm regression tests:
* deploy squid
* configure squid to accept only authorized users (from particular subnet/host)
* set Pulp instance firewall to drop non-proxied HTTPS traffic `iptables -I OUTPUT 1  \! -d squid.example.com -p tcp  --dport 443 -j DROP`
* assert squid service works on the Pulp instance `https_proxy='https://user:passwd@squid.example.com:3128' curl https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/repodata/repomd.xml`
* run rpm regression scenario
* unset firewall changes on Pulp instance

The reasons for this being rather a deployment/configuration issue are:
* very cumbersome and fragile set-up to perform in a testcase
* any content test case could be run with the proxy settings (e.g. puppet)

I've enhanced the `yum_create_repo` function in the Commit d39451287 so that if a proxy role is linked to a repo, the configuration is propagated to the  repo importer.
Thus it is now possible to run any automation test case with a proxy:
```
# cat inventory.yaml
# ----%<------------
 proxy: &PROXY
    host: "https://proxy.example.com"
    port: 3128
    username: squid
    password: squid

  repos:
  - &ZOO
    id: zoo
    type: rpm
    feed: "https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/"
    display_name: ZOo rEPO
    proxy: *PROXY
    tags: [default, small, demo, rpm]
```
I'll add the feature to `create_puppet_repo` and `create_docker_repo`.
Ideally, we'd also have an Ansible playbook to deploy Pulp together with Squid including any sanity steps.
Please, let me know, what you think about this.
